-- MySQL Script generated by MySQL Workbench
-- Wed 30 May 2018 01:23:00 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Alergenos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alergenos` (
  `NombreAlergeno` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  PRIMARY KEY (`NombreAlergeno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Nombre` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `Contrasena` VARCHAR(20) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `Edad` INT(11) NOT NULL,
  `Correo` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `Sexo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Contrasena`, `Correo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Dieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dieta` (
  `Usuario_Correo` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `Usuario_Contrasena` VARCHAR(20) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  PRIMARY KEY USING BTREE (`Usuario_Correo`, `Usuario_Contrasena`),
  INDEX `Dieta_Usuario_FK` (`Usuario_Contrasena` ASC, `Usuario_Correo` ASC),
  CONSTRAINT `Dieta_Usuario_FK`
    FOREIGN KEY (`Usuario_Contrasena` , `Usuario_Correo`)
    REFERENCES `mydb`.`Usuario` (`Contrasena` , `Correo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Platos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Platos` (
  `Nombre` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `Usuario_Correo` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NULL DEFAULT NULL,
  `Usuario_Contrasena` VARCHAR(20) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `Usuario_Correo` (`Usuario_Correo` ASC, `Usuario_Contrasena` ASC),
  CONSTRAINT `Platos_Dieta_Correo`
    FOREIGN KEY (`Usuario_Correo` , `Usuario_Contrasena`)
    REFERENCES `mydb`.`Dieta` (`Usuario_Correo` , `Usuario_Contrasena`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Alimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alimentos` (
  `NombreAlimento` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `Grasas` INT(11) NOT NULL,
  `Carbohidratos` INT(11) NOT NULL,
  `Proteinas` INT(11) NOT NULL,
  `Calorias` INT(11) NOT NULL,
  `Precio` INT(11) NOT NULL,
  `Platos_Nombre` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  PRIMARY KEY (`NombreAlimento`),
  INDEX `Platos_Nombre` (`Platos_Nombre` ASC),
  CONSTRAINT `Ingredientes_Platos_FK`
    FOREIGN KEY (`Platos_Nombre`)
    REFERENCES `mydb`.`Platos` (`Nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Contener`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contener` (
  `Alimentos_NombreAlimento` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `Alergenos_NombreAlergeno` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  PRIMARY KEY (`Alimentos_NombreAlimento`, `Alergenos_NombreAlergeno`),
  INDEX `Ingredientes_NombreIngrediente` (`Alimentos_NombreAlimento` ASC),
  INDEX `Alergenos_NombreAlergeno` (`Alergenos_NombreAlergeno` ASC),
  CONSTRAINT `Contener_Alergenos_FK`
    FOREIGN KEY (`Alergenos_NombreAlergeno`)
    REFERENCES `mydb`.`Alergenos` (`NombreAlergeno`),
  CONSTRAINT `Contener_Alimentos_FK`
    FOREIGN KEY (`Alimentos_NombreAlimento`)
    REFERENCES `mydb`.`Alimentos` (`NombreAlimento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
